// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGg4GVhuOQHH-zZDk-YreU4VvzwHEIMkU',
    appId: '1:605393192584:web:16b672c8265fa6cc6bc13d',
    messagingSenderId: '605393192584',
    projectId: 'papayabuddy-cecbc',
    authDomain: 'papayabuddy-cecbc.firebaseapp.com',
    storageBucket: 'papayabuddy-cecbc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANT6ybyk3XBUIYQ3rumDHKdffYvIIc_Ig',
    appId: '1:605393192584:android:9a6ebda5e288db8d6bc13d',
    messagingSenderId: '605393192584',
    projectId: 'papayabuddy-cecbc',
    storageBucket: 'papayabuddy-cecbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHvf2_FEJPLR4w7za4YXQNSX5c-Tq159o',
    appId: '1:605393192584:ios:720d8997ed452d626bc13d',
    messagingSenderId: '605393192584',
    projectId: 'papayabuddy-cecbc',
    storageBucket: 'papayabuddy-cecbc.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHvf2_FEJPLR4w7za4YXQNSX5c-Tq159o',
    appId: '1:605393192584:ios:720d8997ed452d626bc13d',
    messagingSenderId: '605393192584',
    projectId: 'papayabuddy-cecbc',
    storageBucket: 'papayabuddy-cecbc.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGg4GVhuOQHH-zZDk-YreU4VvzwHEIMkU',
    appId: '1:605393192584:web:62d4bbe438dd66c36bc13d',
    messagingSenderId: '605393192584',
    projectId: 'papayabuddy-cecbc',
    authDomain: 'papayabuddy-cecbc.firebaseapp.com',
    storageBucket: 'papayabuddy-cecbc.firebasestorage.app',
  );
}
